language: java
before_deploy:
  - pip install cloudsmith-cli
  - mvn help:evaluate -N -Dexpression=project.artifactId|grep -v '\['
  - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
  - export ARTIFACT_FINAL_NAME=concat($(mvn help:evaluate -N -Dexpression=project.artifactId|grep -v '\['), "-", $(mvn help:evaluate -N -Dexpression=project.version|grep -v '\['), ".jar")
deploy:
  - provider: script
  - script: cloudsmith push maven eisti-sib/sib-2019 $ARTIFACT_FINAL_NAME
  - on:
    branch: master  
