language: java
before_deploy:
  - pip install --user cloudsmith-cli
  - export ARTIFACT_FINAL_NAME="test.jar"
deploy:
  - provider: script
  - script: cloudsmith push maven eisti-sib/sib-2019 $ARTIFACT_FINAL_NAME
  - on:
    branch: master  
